// ============================================================
// DarkFlix - Dados Iniciais de Filmes e Séries
// ============================================================

const DEFAULT_MOVIES = [
  {
    id: 1,
    title: "Interestelar",
    year: 2014,
    duration: "2h 49m",
    rating: 8.7,
    type: "movie",
    featured: true,
    videoType: "url",
    genres: ["Ficção Científica", "Drama", "Aventura"],
    description: "As reservas naturais da Terra estão chegando ao fim e um grupo de astronautas recebe a missão de verificar possíveis planetas para receberem a população mundial, garantindo a sobrevivência da espécie humana.",
    poster: "https://image.tmdb.org/t/p/w500/nCbkOyOMTEwlEV0LtCObySSRFhk.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/xu9zaAevzQ5nnrsXN6JcahLnG4i.jpg",
    video: "https://www.youtube.com/embed/zSWdZVtXT7E?autoplay=1"
  },
  {
    id: 2,
    title: "O Poderoso Chefão",
    year: 1972,
    duration: "2h 55m",
    rating: 9.2,
    type: "movie",
    featured: false,
    videoType: "url",
    genres: ["Crime", "Drama"],
    description: "Uma família de Nova York, durante os anos 40, é chefiada por Don Vito Corleone. Ele é o chefão da máfia e comanda com mão de ferro os negócios ilícitos, se tornando o homem mais poderoso da cidade.",
    poster: "https://image.tmdb.org/t/p/w500/oJagOzBu9Rdd9BrciseCm3U3MCU.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/tmU7GeKVybMWFButWEGl2M4GeiP.jpg",
    video: "https://www.youtube.com/embed/UaVTIH8mujA?autoplay=1"
  },
  {
    id: 3,
    title: "Batman: O Cavaleiro das Trevas",
    year: 2008,
    duration: "2h 32m",
    rating: 9.0,
    type: "movie",
    featured: false,
    videoType: "url",
    genres: ["Ação", "Crime", "Drama"],
    description: "Com a ajuda do tenente Jim Gordon e do promotor público Harvey Dent, Batman enfrenta o Coringa, um gênio do crime que semeia o caos e a destruição em Gotham City.",
    poster: "https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911BytUESw3KFkt.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/nMKdUUepR0i5zn0y1T4CsSB5ez.jpg",
    video: "https://www.youtube.com/embed/EXeTwQWrcwY?autoplay=1"
  },
  {
    id: 4,
    title: "Clube da Luta",
    year: 1999,
    duration: "2h 19m",
    rating: 8.8,
    type: "movie",
    featured: false,
    videoType: "url",
    genres: ["Drama", "Thriller"],
    description: "Um homem deprimido que sofre de insônia conhece Tyler Durden, um vendedor de sabão despreocupado. Juntos, eles formam um clube do luta clandestino que evolui para algo muito mais perigoso.",
    poster: "https://image.tmdb.org/t/p/w500/pB8BM7pdSp6B6Ih7QZ4DrQ3PmJK.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/hZkgoQYus5dXo3H8T7CYV2UImTl.jpg",
    video: "https://www.youtube.com/embed/qtRKdVHc-cE?autoplay=1"
  },
  {
    id: 5,
    title: "Inception: A Origem",
    year: 2010,
    duration: "2h 28m",
    rating: 8.8,
    type: "movie",
    featured: false,
    videoType: "url",
    genres: ["Ficção Científica", "Ação", "Thriller"],
    description: "Dom Cobb é um ladrão habilidoso que rouba segredos corporativos usando tecnologia de compartilhamento de sonhos. Ele recebe a chance de ter sua vida de volta se conseguir realizar o inverso: implantar uma ideia na mente de alguém.",
    poster: "https://image.tmdb.org/t/p/w500/ljsZTbVsrQSqZgWeep2B1QiDKuh.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/8ZTVqvKDQ8emSGUEMjsS4yHAwrp.jpg",
    video: "https://www.youtube.com/embed/YoHD9XEInc0?autoplay=1"
  },
  {
    id: 6,
    title: "Matrix",
    year: 1999,
    duration: "2h 16m",
    rating: 8.7,
    type: "movie",
    featured: false,
    videoType: "url",
    genres: ["Ficção Científica", "Ação"],
    description: "O hacker Neo descobre que o mundo em que vive é uma realidade simulada criada por máquinas. Guiado por Morpheus, ele embarca em uma jornada para libertar a humanidade.",
    poster: "https://image.tmdb.org/t/p/w500/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/fNG7i7RqMErkcqhohV2a6cV1Ehy.jpg",
    video: "https://www.youtube.com/embed/vKQi3bBA1y8?autoplay=1"
  },
  {
    id: 7,
    title: "Parasita",
    year: 2019,
    duration: "2h 12m",
    rating: 8.5,
    type: "movie",
    featured: false,
    videoType: "url",
    genres: ["Thriller", "Comédia", "Drama"],
    description: "A família Kim, que vive em um porão apertado, elabora um plano para se infiltrar na casa da rica família Park. Uma escalada de eventos inesperados mostra que as diferenças sociais têm consequências devastadoras.",
    poster: "https://image.tmdb.org/t/p/w500/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/TU9NIjwzjoKPwQHoHshkFcQUCG.jpg",
    video: "https://www.youtube.com/embed/5xH0HfJHsaY?autoplay=1"
  },
  {
    id: 8,
    title: "Vingadores: Ultimato",
    year: 2019,
    duration: "3h 01m",
    rating: 8.4,
    type: "movie",
    featured: false,
    videoType: "url",
    genres: ["Ação", "Aventura", "Ficção Científica"],
    description: "Após os eventos devastadores de Thanos, os Vingadores restantes devem se reunir mais uma vez para desfazer suas ações e restaurar a ordem no universo, custando o que for necessário.",
    poster: "https://image.tmdb.org/t/p/w500/q6725aR8Zs4IwGMXzZT2CBlKAU.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/7RyHsO4yDXtBv1zUU3mTpHeQ0d5.jpg",
    video: "https://www.youtube.com/embed/TcMBFSGVi1c?autoplay=1"
  },
  {
    id: 9,
    title: "Duna",
    year: 2021,
    duration: "2h 35m",
    rating: 8.0,
    type: "movie",
    featured: false,
    videoType: "url",
    genres: ["Ficção Científica", "Aventura", "Drama"],
    description: "Paul Atreides, um jovem brilhante e talentoso, nascido para um grande destino, viaja ao planeta mais perigoso do universo para garantir o futuro de sua família e de seu povo.",
    poster: "https://image.tmdb.org/t/p/w500/d5NXSklXo0qyIYkgV94XAgMIckC.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/jYEW5xZkZk2WTrdbMGAPFuBqbDc.jpg",
    video: "https://www.youtube.com/embed/n9xhJrPXop4?autoplay=1"
  },
  {
    id: 10,
    title: "Oppenheimer",
    year: 2023,
    duration: "3h 00m",
    rating: 8.4,
    type: "movie",
    featured: false,
    videoType: "url",
    genres: ["Drama", "História"],
    description: "A história do físico J. Robert Oppenheimer e o seu papel no desenvolvimento da bomba atômica durante a Segunda Guerra Mundial, além das consequências morais devastadoras dessa criação.",
    poster: "https://image.tmdb.org/t/p/w500/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/nb3xI8XI3w4pMVZ38VijbsyBqP4.jpg",
    video: "https://www.youtube.com/embed/uYPbbksJxIg?autoplay=1"
  },
  {
    id: 11,
    title: "Stranger Things",
    year: 2016,
    duration: "4 Temporadas",
    rating: 8.7,
    type: "series",
    featured: false,
    videoType: "url",
    genres: ["Ficção Científica", "Terror", "Drama"],
    description: "Quando um garoto desaparece misteriosamente, seus amigos, sua mãe e o xerife da cidade investigam o caso, descobrindo experiências secretas do governo, forças sobrenaturais e uma garota estranha.",
    poster: "https://image.tmdb.org/t/p/w500/49WJfeN0moxb9IPfGn8AIqMGskD.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/56v2KjBlYj7y8VJOzXkTGg3Zfak.jpg",
    video: "https://www.youtube.com/embed/b9EkMc79ZSU?autoplay=1"
  },
  {
    id: 12,
    title: "Breaking Bad",
    year: 2008,
    duration: "5 Temporadas",
    rating: 9.5,
    type: "series",
    featured: false,
    videoType: "url",
    genres: ["Crime", "Drama", "Thriller"],
    description: "Walter White, um professor de química do ensino médio que descobre ter câncer terminal, decide começar a produzir metanfetamina com um ex-aluno para garantir o futuro financeiro de sua família.",
    poster: "https://image.tmdb.org/t/p/w500/ztkUQFLlC19CCMYHW73GM6EQ3GP.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/gc8PfyTqzqltKMCr3gLEoNIt7CB.jpg",
    video: "https://www.youtube.com/embed/HhesaQXLuRY?autoplay=1"
  },
  {
    id: 13,
    title: "The Witcher",
    year: 2019,
    duration: "3 Temporadas",
    rating: 8.2,
    type: "series",
    featured: false,
    videoType: "url",
    genres: ["Fantasia", "Ação", "Aventura"],
    description: "Geralt de Rívia, um caçador de monstros mutante, luta para encontrar seu lugar em um mundo onde as pessoas muitas vezes se mostram mais perversas do que os monstros que ele enfrenta.",
    poster: "https://image.tmdb.org/t/p/w500/7vjaCdMw15FEbXyLQTVa04URsPm.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/jBJWaqoSCiARWtfV0GlqHrcdiJq.jpg",
    video: "https://www.youtube.com/embed/ndl1W4ltcmg?autoplay=1"
  },
  {
    id: 14,
    title: "Peaky Blinders",
    year: 2013,
    duration: "6 Temporadas",
    rating: 8.8,
    type: "series",
    featured: false,
    videoType: "url",
    genres: ["Crime", "Drama"],
    description: "Na Birmingham pós-Primeira Guerra, Tommy Shelby lidera os Peaky Blinders, uma das gangues mais temidas da Inglaterra, enquanto tenta expandir seu império e manter a família unida.",
    poster: "https://image.tmdb.org/t/p/w500/vUUqzWa2LnHIVqkaKVlVGkVcZIW.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/wiE9doxiLwq3WCGamDIOb2PqBqc.jpg",
    video: "https://www.youtube.com/embed/oVzVdvGIC7U?autoplay=1"
  },
  {
    id: 15,
    title: "John Wick 4: Baba Yaga",
    year: 2023,
    duration: "2h 49m",
    rating: 7.7,
    type: "movie",
    featured: false,
    videoType: "url",
    genres: ["Ação", "Thriller", "Crime"],
    description: "John Wick enfrenta seu adversário mais letal até agora. Com o preço por sua cabeça cada vez mais alto, ele busca aliados e enfrenta a Alta Mesa em batalhas épicas ao redor do mundo.",
    poster: "https://image.tmdb.org/t/p/w500/vZloFAK7NmvMGKE7LsyBGSNiVJt.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/7I6VUdPj6tQECNHdviJkUHD2u89.jpg",
    video: "https://www.youtube.com/embed/qEVUtrk8_B4?autoplay=1"
  },
  {
    id: 16,
    title: "Blade Runner 2049",
    year: 2017,
    duration: "2h 44m",
    rating: 8.0,
    type: "movie",
    featured: false,
    videoType: "url",
    genres: ["Ficção Científica", "Drama", "Thriller"],
    description: "O oficial K da LAPD descobre um segredo enterrado que pode mergulhar o que resta da sociedade no caos. Sua descoberta o leva a encontrar Rick Deckard, um ex-blade runner desaparecido há 30 anos.",
    poster: "https://image.tmdb.org/t/p/w500/gajva2L0rPYkEWjzgFlBXCAVBE5.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/sAtoMqDVhNDQBc3QJL3RF6hlhGq.jpg",
    video: "https://www.youtube.com/embed/gCcx85zbxz4?autoplay=1"
  },
  {
    id: 17,
    title: "A Casa do Dragão",
    year: 2022,
    duration: "2 Temporadas",
    rating: 8.4,
    type: "series",
    featured: false,
    videoType: "url",
    genres: ["Fantasia", "Drama", "Ação"],
    description: "Ambientada 200 anos antes dos eventos de Game of Thrones, a série conta a história da Casa Targaryen e da guerra civil que ficou conhecida como a Dança dos Dragões.",
    poster: "https://image.tmdb.org/t/p/w500/z2yahl2uefxDCl0nogcRBstwruJ.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/etj8E2o0Bud0HkONVQPjyCkIvpv.jpg",
    video: "https://www.youtube.com/embed/DotnJ7tTA34?autoplay=1"
  },
  {
    id: 18,
    title: "Gladiador II",
    year: 2024,
    duration: "2h 28m",
    rating: 7.0,
    type: "movie",
    featured: false,
    videoType: "url",
    genres: ["Ação", "Aventura", "Drama"],
    description: "Lucius, o filho de Lucilla, é forçado a entrar no Coliseu depois que seu lar é conquistado. Com fúria em seu coração, ele deve lutar pelo futuro de Roma enfrentando tiranos e imperadores corruptos.",
    poster: "https://image.tmdb.org/t/p/w500/2cxhvwyEwRlysAmRH4iodkvo0z5.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/euYIwmwkmz95mnXvufEmbL6ovhZ.jpg",
    video: "https://www.youtube.com/embed/4rgYUipGJNo?autoplay=1"
  }
];

// Gêneros disponíveis
const ALL_GENRES = [
  "Ação", "Aventura", "Comédia", "Crime", "Drama",
  "Fantasia", "Ficção Científica", "História", "Terror", "Thriller"
];
